//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Webapi.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Webapi.Common.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_tai_khoan.
        /// </summary>
        public static string accountExcelFile {
            get {
                return ResourceManager.GetString("accountExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string accountExcelSheet {
            get {
                return ResourceManager.GetString("accountExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH_SÁCH_TÀI_KHOẢN.
        /// </summary>
        public static string accountExcelTitle {
            get {
                return ResourceManager.GetString("accountExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới không thành công.
        /// </summary>
        public static string createFail {
            get {
                return ResourceManager.GetString("createFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thành công.
        /// </summary>
        public static string createSuccess {
            get {
                return ResourceManager.GetString("createSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        /// </summary>
        public static string deleteFail {
            get {
                return ResourceManager.GetString("deleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string deleteSuccess {
            get {
                return ResourceManager.GetString("deleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate AccountNumber.
        /// </summary>
        public static string devMsg_DuplicateAccount {
            get {
                return ResourceManager.GetString("devMsg.DuplicateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate EmployeeCode.
        /// </summary>
        public static string devMsg_DuplicateEmployee {
            get {
                return ResourceManager.GetString("devMsg.DuplicateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catched an exception in EmployeeController.
        /// </summary>
        public static string devMsg_Exception {
            get {
                return ResourceManager.GetString("devMsg.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to over.
        /// </summary>
        public static string devMsg_InvalidLength {
            get {
                return ResourceManager.GetString("devMsg.InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passing invalid parameter.
        /// </summary>
        public static string devMsg_InvalidParam {
            get {
                return ResourceManager.GetString("devMsg.InvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  field are required.
        /// </summary>
        public static string devMsg_RequiredField {
            get {
                return ResourceManager.GetString("devMsg.RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh_sach_nhan_vien.
        /// </summary>
        public static string employeeExcelFile {
            get {
                return ResourceManager.GetString("employeeExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên.
        /// </summary>
        public static string employeeExcelSheet {
            get {
                return ResourceManager.GetString("employeeExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NHÂN VIÊN.
        /// </summary>
        public static string employeeExcelTitle {
            get {
                return ResourceManager.GetString("employeeExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách phòng ban.
        /// </summary>
        public static string excelExportDepartmentFileName {
            get {
                return ResourceManager.GetString("excelExportDepartmentFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách nhân viên.
        /// </summary>
        public static string excelExportEmployeeFileName {
            get {
                return ResourceManager.GetString("excelExportEmployeeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Một số trường thông tin không hợp lệ.
        /// </summary>
        public static string invalidField {
            get {
                return ResourceManager.GetString("invalidField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu_chi_tien_mat.
        /// </summary>
        public static string paymentExcelFile {
            get {
                return ResourceManager.GetString("paymentExcelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU CHI TIỀN MẶT.
        /// </summary>
        public static string paymentExcelSheet {
            get {
                return ResourceManager.GetString("paymentExcelSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THU CHI TIỀN MẶT.
        /// </summary>
        public static string paymentExcelTitle {
            get {
                return ResourceManager.GetString("paymentExcelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật không thành công.
        /// </summary>
        public static string updateFail {
            get {
                return ResourceManager.GetString("updateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cập nhật thành công.
        /// </summary>
        public static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số tài khoản đã tồn tại vui lòng kiểm tra lại.
        /// </summary>
        public static string userMsg_DuplicateAccount {
            get {
                return ResourceManager.GetString("userMsg.DuplicateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại.
        /// </summary>
        public static string userMsg_DuplicateEmployee {
            get {
                return ResourceManager.GetString("userMsg.DuplicateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng từ đã tồn tại vui lòng kiểm tra lại.
        /// </summary>
        public static string userMsg_DuplicateReceiptPayment {
            get {
                return ResourceManager.GetString("userMsg.DuplicateReceiptPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, liên hệ MISA.
        /// </summary>
        public static string userMsg_Exception {
            get {
                return ResourceManager.GetString("userMsg.Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vượt quá.
        /// </summary>
        public static string userMsg_InvalidLength {
            get {
                return ResourceManager.GetString("userMsg.InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ.
        /// </summary>
        public static string userMsg_InvalidParam {
            get {
                return ResourceManager.GetString("userMsg.InvalidParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  không thể để trống.
        /// </summary>
        public static string userMsg_RequiredField {
            get {
                return ResourceManager.GetString("userMsg.RequiredField", resourceCulture);
            }
        }
    }
}
